# Generated by Django 6.0.1 on 2026-01-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
            ],
        ),
    ]
