# Generated by Django 6.0.1 on 2026-02-11 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0003_alter_appointment_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card'), ('online', 'Online Transfer'), ('onhand', 'On Hand')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('charge', 'Charge'), ('paid', 'Paid')], max_length=10),
        ),
    ]
