# Generated by Django 6.0.1 on 2026-02-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'serial_number']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'serial_number')},
        ),
    ]
