# Generated by Django 6.0.1 on 2026-02-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_options_appointment_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='serial_number',
            field=models.PositiveIntegerField(),
        ),
    ]
