# Generated by Django 6.0.1 on 2026-04-23 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescription_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='oe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PrescriptionInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.investigation')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='prescriptions.prescription')),
            ],
        ),
    ]
